language: generic

services:
  - docker
before_install:
  - docker build -t guillaumeo19/html_test .

before_deploy: "echo 'ready?'"

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
  region: "us-east-1"
  app: "html-test"
  env: "HtmlTest-env"
  bucket_name: "html-test"
